language: java

notifications:
  email: false

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository

before_script:
  - pip install --user codecov

install: mvn dependency:resolve dependency:resolve-plugins -V -B -P ci-coverage,ossrh-deploy

script:
  - 'sh travis.sh'

after_success:
  - codecov
