language: java

notifications:
  email: false

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository

before_script:
  - pip install --user codecov

install: mvn dependency:resolve dependency:resolve-plugins -V -B -P ci-coverage,ossrh-deploy

script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && mvn deploy -B -P ci-coverage,ossrh-deploy --settings settings.xml || mvn verify -B -P ci-coverage'

after_success:
  - codecov
